// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLYQ8UN36FypWe5uPYhC4k2vldgOM22o',
    appId: '1:405880404881:web:2ae5ba3e6fd7e57e00f830',
    messagingSenderId: '405880404881',
    projectId: 'medicine-app-77f58',
    authDomain: 'medicine-app-77f58.firebaseapp.com',
    storageBucket: 'medicine-app-77f58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFjENMzjAlD12WSyjXHUKYvoC_Pi9h-b0',
    appId: '1:405880404881:android:237f5765625b299b00f830',
    messagingSenderId: '405880404881',
    projectId: 'medicine-app-77f58',
    storageBucket: 'medicine-app-77f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2Ll9gvoNKhCX43BRni3IFA2EafJHEGw',
    appId: '1:405880404881:ios:0b0633003ad2a63f00f830',
    messagingSenderId: '405880404881',
    projectId: 'medicine-app-77f58',
    storageBucket: 'medicine-app-77f58.appspot.com',
    iosBundleId: 'com.example.pills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2Ll9gvoNKhCX43BRni3IFA2EafJHEGw',
    appId: '1:405880404881:ios:f36295befa9461a300f830',
    messagingSenderId: '405880404881',
    projectId: 'medicine-app-77f58',
    storageBucket: 'medicine-app-77f58.appspot.com',
    iosBundleId: 'com.example.pills.RunnerTests',
  );
}
